services:
  app:
    build:
      context: .
    container_name: book-tracker-service
    ports:
      - "8081:8081"
    depends_on:
      - db-books
    restart: always
  db-books:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: BOOK-TRACKER
    ports:
      - "5433:5432"